docs: add slides of OSS Europe talk
ZEISS/fretish_robot pull request #12
Opened 2024-09-20 09:40 UTC by schlotter

2024-09-20 11:29 UTC, MP-StefanKraus requested changes

2024-09-20 11:29 UTC, MP-StefanKraus commented on README.md
> +Slides and recordings related to this project can be can be found [in the `talks` directory](talks/).
'can be' twice

2024-09-20 11:29 UTC, MP-StefanKraus commented on talks/README.md
> +* **Slides**: [20240917 OSS Europe Level Up Your Embedded Testing Game.pdf](20240917%20OSS%20Europe%20Level%20Up%20Your%20Embedded%20Testing%20Game.pdf)
I would probably put that one between 'Event' and 'Abstract', as it gets easily overseen otherwise.

2024-09-20 13:11 UTC, schlotter commented on README.md
> +Slides and recordings related to this project can be can be found [in the `talks` directory](talks/).
Oops, corrected :-)

2024-09-23 07:35 UTC, MP-StefanKraus approved these changes

2024-09-23 07:35 UTC, merged